### ISSUE TITLE
RA3 deployement - MQTT Question

### ISSUE THREAD

**Issue by MouseRatt** [terafin/mqtt-lutron-leap-bridge#4]
Hi @terafin awesome looking project! Had a few hiccups getting this running, but I think i have it figured out now.

However, I have found that the mqtt bridge looks for commands published to '/zone/' while the MQTT provides status from the RA3 hub using '/zones/'  -- took me a few mins of looking through the code to finally realize why my published MQTT commands were failing. not sure if this is intentional?

**Comment by MouseRatt** [comment]
So it looks like i pulled the keys and certs - but i get a type error:
[ERROR] logger - error: TypeError: Cannot read properties of undefined (reading 'AreaStatuses')

Do i perhaps have something configured incorrectly?

**Comment by MouseRatt** [comment]
@terafin it looks like I got it working, I pulled the certificates again and it started working correctly. Seems I had some sort of authentication issue and had trouble connecting to the Leap API.

Can I change the state of the light using this MQTT docker? I tried to publish state changes to the RA3 but wasn't able to turn on or off my lights using that technique

**Comment by terafin** [comment]
@MouseRatt Thanks for the comment! Honestly, totally not intentional. I'll move this to zone for both to follow the ra3 structure! I only used zones, as it matched my own personal MQTT setup.

Please do file more issues (Docs are needed too!). I'm waiting on a bunch more (50+) ra3 switches to get setup, and want to make sure this works well (I only have 10 or so running now)!

**Comment by terafin** [comment]
As for changing state of the lights, yes! Let me document that.

**Comment by MouseRatt** [comment]
Awesome thanks for the change - pulling it all into Homeassistant through my mqtt broker and it is working amazingly! I am going to order some occupancy sensors as well and can test those also. I'm only at about 10 dimmer + switches but will also be adding about 50-60 more also.

**Comment by MouseRatt** [comment]
@terafin any plans for adding RA2 fan switch support to the main library? Or ra3 keypad support? Not sure if you have AC or DC fans in your house but thought I'd ask. I am happy to help implement support in any way possible, but not sure that I have the know-how to implement it myself
